#!/usr/bin/env sh

# compile {filename} [{filename} ...]
# compile all

compile_file () {
    target=$1
    printf "Compiling $target ... "
    cat $target | sed 's/<x>/█/g' > ../$target
    echo "Done"
}

skip_file () {
    echo "Skip $1"
}

compile_all () {
    for i in $(ls *.rst); do
        if [ "$i" == "template.rst" ]; then
            skip_file $i
        elif [ "$i" == "terms.rst" ]; then
            skip_file $i
        else
            compile_file $i
        fi
    done
    exit
}

if [ $# -eq 0 ]; then
    compile_all
    exit
fi

while [ $# -gt 0 ]; do
    target=$1

    if [ "=$target" = "=" ]; then
        echo "Empty target, abort"
        exit
    fi

    if [ "=$target" = "=all" ]; then
        compile_all
    fi

    compile_file $target
    shift
done
