#!/usr/bin/env sh

# compile {filename} [{filename} ...]
# compile all

check_dirty () {
    if [ $1 -nt ../$1 ]; then
        echo 1
        return 1
    fi
    echo 0
    return 0
}

compile_file () {
    target=$1
    if [ $(check_dirty $target) -eq 1 ]; then
        printf "\033[1;31m[compile] $target ... \033[m"
        cat $target | sed 's/<x>/█/g' > ../$target
        printf "\r\033[1;32m[compile] $target ... done\033[m\n"
    else
        skip_file $target
    fi
}

skip_file () {
    echo "[ skip  ] $1"
}

compile_all () {
    for i in $(ls *.rst); do
        if [ "=$i" = "=template.rst" ]; then
            skip_file $i
        elif [ "=$i" = "=terms.rst" ]; then
            skip_file $i
        else
            compile_file $i
        fi
    done
    exit
}

if [ $# -eq 0 ]; then
    compile_all
    exit
fi

while [ $# -gt 0 ]; do
    target=$1

    if [ "=$target" = "=" ]; then
        echo "Empty target, abort"
        exit
    fi

    if [ "=$target" = "=all" ]; then
        compile_all
    fi

    compile_file $target
    shift
done
